GenshinTierList/Models/TierList.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace AspNetCoreWebApp.Models
{
    public class TierList
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 3)]
        public string Name { get; set; }

        [Required]
        public Atribute Atribute { get; set; }

        [Required]
        public string Tier { get; set; }

        [Required]
        [DataType(DataType.Url)]
        [Display(Name = "Wiki link")]
        public string WikiUrl { get; set; }

        [Required]
        [DataType(DataType.ImageUrl)]
        [Display(Name = "Character")]
        public string ImageUrl { get; set; }
    }
}

GenshinTierList/Controllers/TierListsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AspNetCoreWebApp.Models;
using NuGet.Packaging.Signing;

namespace GenshinTierList.Controllers
{
    public class TierListsController : Controller
    {
        private readonly GenshinTierListContext _context;

        public TierListsController(GenshinTierListContext context)
        {
            _context = context;
        }

        // GET: TierLists
        /*public async Task<IActionResult> Index()
        {
              return View(await _context.TierList.ToListAsync());
        }*/
        public async Task<IActionResult> Index(string searchString)
        {
            if (_context.TierList == null)
            {
                return Problem("Entity set 'MvcMovieContext.TierList'  is null.");
            }

            var tierLists = from m in _context.TierList
                         select m;

            if (!string.IsNullOrEmpty(searchString))
            {
                tierLists = tierLists.Where(s => s.Name!.Contains(searchString));
            }

            return View(await tierLists.ToListAsync());
        }

        // GET: TierLists/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TierList == null)
            {
                return NotFound();
            }

            var tierList = await _context.TierList
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tierList == null)
            {
                return NotFound();
            }

            return View(tierList);
        }

        // GET: TierLists/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TierLists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Atribute,Tier,WikiUrl,ImageUrl")] TierList tierList)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tierList);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tierList);
        }

        // GET: TierLists/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TierList == null)
            {
                return NotFound();
            }

            var tierList = await _context.TierList.FindAsync(id);
            if (tierList == null)
            {
                return NotFound();
            }
            return View(tierList);
        }

        // POST: TierLists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Atribute,Tier,WikiUrl,ImageUrl")] TierList tierList)
        {
            if (id != tierList.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tierList);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TierListExists(tierList.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tierList);
        }

        // GET: TierLists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TierList == null)
            {
                return NotFound();
            }

            var tierList = await _context.TierList
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tierList == null)
            {
                return NotFound();
            }

            return View(tierList);
        }

        // POST: TierLists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TierList == null)
            {
                return Problem("Entity set 'GenshinTierListContext.TierList'  is null.");
            }
            var tierList = await _context.TierList.FindAsync(id);
            if (tierList != null)
            {
                _context.TierList.Remove(tierList);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TierListExists(int id)
        {
          return _context.TierList.Any(e => e.Id == id);
        }
    }
}

GenshinTierList/Views/TierLists/Create.cshtml
@using AspNetCoreWebApp.Models
@model AspNetCoreWebApp.Models.TierList

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TierList</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Atribute" class="control-label"></label>
                <select asp-for="Atribute" asp-items="Html.GetEnumSelectList<Atribute>()" class="form-control">
                    <option value=""></option>
                </select>
                <span asp-validation-for="Atribute" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tier" class="control-label"></label>
                <input asp-for="Tier" class="form-control" />
                <span asp-validation-for="Tier" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WikiUrl" class="control-label"></label>
                <input asp-for="WikiUrl" class="form-control" />
                <span asp-validation-for="WikiUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GenshinTierList/Views/TierLists/Delete.cshtml
@model AspNetCoreWebApp.Models.TierList

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TierList</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Atribute)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Atribute)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tier)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tier)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WikiUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WikiUrl)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GenshinTierList/Views/TierLists/Details.cshtml
@model AspNetCoreWebApp.Models.TierList

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TierList</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Atribute)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Atribute)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tier)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tier)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WikiUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WikiUrl)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

GenshinTierList/Views/TierLists/Edit.cshtml
@using AspNetCoreWebApp.Models
@model AspNetCoreWebApp.Models.TierList

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TierList</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Atribute" class="control-label"></label>
                <select asp-for="Atribute" asp-items="Html.GetEnumSelectList<Atribute>()" class="form-control">
                    <option value=""></option>
                </select>
                <span asp-validation-for="Atribute" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tier" class="control-label"></label>
                <input asp-for="Tier" class="form-control" />
                <span asp-validation-for="Tier" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WikiUrl" class="control-label"></label>
                <input asp-for="WikiUrl" class="form-control" />
                <span asp-validation-for="WikiUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GenshinTierList/Views/TierLists/Index.cshtml
@model IEnumerable<AspNetCoreWebApp.Models.TierList>

@{
    ViewData["Title"] = "Index";
}

<h1>Character</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="TierLists" asp-action="Index" method="get">
    <p>
        Name: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ImageUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Atribute)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tier)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WikiUrl)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
                    @if (item.ImageUrl != null)
                    {
                        <img src="@Url.Content(item.ImageUrl)" alt="Image" />
                    }
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Atribute)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tier)
            </td>
            <td>
                <a href=@item.WikiUrl target='_blank'>@item.Name</a>
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>